(define-module (objects backdrop)
  #:use-module (ray)
  #:use-module (vec3)
  #:use-module (utils)
  #:use-module (image)
  #:use-module (hittables))

(define (shader hrec)
  (define one (vec3 1 1 1))
  (define a (* (+ (vy (unit-vector (get-normal hrec))) 1)
	       .5))
  (define color (vec3 .5 .7 1.))
  (vscale! one (- 1. a))
  (vscale! color a)
  (vec3->color (v3-add one color)))

(define-public (backdrop-collider)
  (hittable (lambda (ray hrec)
	      (set-t! hrec 9999999999.)
	      (set-normal! hrec
			   (vx (dir ray))
			   (vy (dir ray))
			   (vz (dir ray)))
	      hrec)
	    shader))
