(define-module (objects backdrop)
  #:use-module (ray)
  #:use-module (vec3)
  #:use-module (utils)
  #:use-module (image)
  #:use-module (hittables))

(define (shader hrec)
  (define one (vec3 1 1 1))
  (define a (vscale (v3-add (unit-vector (get-normal hrec)) one)
		    .5))
  (define v1 (vscale a (vec3->color (vec3 -1 -1 -1))))
  (neg! v1)
  (vscale! v1 (vec3->color (vec3 1 1 1)))
  (define v2 (vscale a (vec3->color (vec3 .5 .7 .1))))
  (vec3->color (v3-add v1 v2)))

(define-public (backdrop-collider)
  (hittable (lambda (ray hrec)
	      (set-t! hrec 9999999999.)
	      (set-normal! hrec
			   (vx (dir ray))
			   (vy (dir ray))
			   (vz (dir ray)))
	      hrec)
	    shader))
